---
abstract: 'Map operating system names to generic types or families'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  constant: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OSType
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  OSType:
    file: lib/OSType.pm
    version: 0.004
recommends: {}
requires:
  Exporter: 0
resources:
  repository: http://github.com/dagolden/ostype
version: 0.004
